# Generated by Django 5.1.7 on 2025-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("doctor", "Doctor"), ("patient", "Patient")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
