# Generated by Django 5.1.7 on 2025-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_user_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="experience_years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="chronic_diseases",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="insurance_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="insurance_provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="patient_profiles/"
            ),
        ),
    ]
