# Generated by Django 5.1.7 on 2025-06-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_doctorprofile_bio_doctorprofile_experience_years_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="chronic_diseases",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="insurance_number",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="insurance_provider",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="profile_picture",
        ),
    ]
