# Generated by Django 5.1.7 on 2025-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_patientprofile_allergies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
