# Generated by Django 5.1.7 on 2025-06-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appoinments", "0002_appointment_diagnosis_appointment_prescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "medicine_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "lab_tests",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="appoinments.appointment",
                    ),
                ),
            ],
        ),
    ]
