# Generated by Django 5.1.7 on 2025-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="consultation_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="lab_tests",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="medicine_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="other_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
