# Generated by Django 5.1.7 on 2025-06-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appoinments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
